apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:dev
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: DATABASE_URL
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: AMQP_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: AWS_REGION
            - name: AWS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: AWS_BUCKET_NAME
