apiVersion: apps/v1
kind: Deployment
metadata:
  name: captions
  labels:
    app: captions
    environment: dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: captions
  template:
    metadata:
      labels:
        app: captions
    spec:
      containers:
        - name: captions
          image: captions-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: container-port
              containerPort: 4000
          envFrom:
            - secretRef:
                name: cluster-secret
            - configMapRef:
                name: cluster-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /ready
              port: container-port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /live
              port: container-port
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            fsGroup: 2000
            allowPrivilegeEscalation: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: captions
                topologyKey: kubernetes.io/hostname
