apiVersion: v1
kind: Service
metadata:
  name: captions
spec:
  type: ClusterIP
  selector:
    app: captions
  ports:
    - name: service-port
      port: 83
      targetPort: container-port
      protocol: TCP
  sessionAffinity: None
