apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: web
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: None
